INSERT INTO `expense_categories` (`id`,`name`) VALUES
(1, 'Income'),
(2, 'Home Expenses'),
(3, 'Daily Living'),
(4, 'Children'),
(5, 'Transportation'),
(6, 'Health'),
(7, 'Insurance'),
(8, 'Education'),
(9, 'Charity/Gift'),
(10, 'Savings'),
(11, 'Obligations'),
(12, 'Business Expense'),
(13, 'Entertainment'),
(14, 'Pets'),
(15, 'Subscriptions'),
(16, 'Vacation'),
(17, 'Miscellaneous');

INSERT INTO `expense_sub_categories` (`id`, `parent_id`, `name`) VALUES
(3, 1, 'Wages & Tips'),
(4, 1, 'Secondary income'),
(5, 1, 'Interest Income'),
(6, 1, 'Dividends'),
(7, 1, 'Gifts Received'),
(8, 1, 'Refunds/Reimbursements'),
(9, 1, 'Transfer from Savings'),
(10, 1, 'Other'),
(11, 2, 'Mortgage/Rent'),
(12, 2, 'Electricity'),
(13, 2, 'Gas/Oil'),
(14, 2, 'Water/Sewer/Trash'),
(15, 2, 'Phone'),
(16, 2, 'Cable/Satellite'),
(17, 2, 'Internet'),
(18, 2, 'Furnishings/Appliances'),
(19, 2, 'Lawn/Garden'),
(20, 2, 'Home Supplies'),
(21, 2, 'Maintenance'),
(22, 2, 'Improvements'),
(23, 2, 'Other'),
(24, 3, 'Groceries'),
(25, 3, 'Personal Supplies'),
(26, 3, 'Clothing'),
(27, 3, 'Cleaning Services'),
(28, 3, 'Dining/Eating Out'),
(29, 3, 'Dry Cleaning'),
(30, 3, 'Salon/Barber'),
(31, 3, 'Other');